[build]
publish = "public"
command = "hugo --gc --minify -b ${DEPLOY_PRIME_URL}"

[[headers]]
  for = "/admin/config.yml"
  [headers.values]
    Content-Type = "text/yaml; charset=utf-8"

[build.environment]
HUGO_VERSION = "0.147.9"

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 200