[build]
publish = "public"
command = "hugo --gc --minify -b ${DEPLOY_PRIME_URL}"

[build.environment]
HUGO_VERSION = "0.147.9"
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200