# Сохраните это как static/admin/config.yml

# 1. Backend (Подключение к Git)
backend:
  name: github  # Используем GitHub
  repo: avtozaper/reklamniki  # Имя вашего репозитория (замените, если нужно)
  branch: main  # Основная ветка для публикации

# 2. Authentication (Авторизация)
# Вам нужно будет настроить Auth Provider, например, через Netlify Identity.
# Если вы хостите на Netlify, используйте git-gateway.
# Если на других платформах, используйте Netlify Identity (см. ниже).
publish_mode: simple # Добавляет возможность черновиков (Workflow)

# 3. Media (Медиафайлы: куда сохранять изображения)
media_folder: "static/uploads"  # Папка, где Netlify CMS будет сохранять загруженные файлы
public_folder: "/uploads"       # Путь, который Hugo будет использовать для доступа к файлам

# 4. Collections (Коллекции контента: определяет, что можно редактировать)
collections:
  - name: "docs"
    label: "Документация"
    folder: "content/docs"
    create: true # Разрешить создание новых страниц
    slug: "{{slug}}"
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Дата", name: "date", widget: "datetime"}
      - {label: "Черновик (Draft)", name: "draft", widget: "boolean", default: false}
      # Настройка меню для Hextra
      - label: "Навигация"
        name: "menu"
        widget: "object"
        fields:
          - {label: "Родительский раздел (Parent)", name: "parent", widget: "string", default: "docs", required: false}
          - {label: "Порядок в меню (Weight)", name: "weight", widget: "number", required: false}
      # Тело статьи (Markdown-редактор)
      - {label: "Содержимое", name: "body", widget: "markdown"}

  - name: "config"
    label: "Настройки сайта"
    files:
      - label: "Общие настройки"
        name: "general"
        file: "hugo.yaml" # Или hugo.toml, если вы используете TOML
        fields:
          - {label: "Заголовок сайта", name: "title", widget: "string"}
          - {label: "Базовый URL", name: "baseURL", widget: "string"}
          # Добавьте сюда другие важные параметры из вашего hugo.yaml