backend:
  name: git-gateway
  branch: main # если у тебя основная ветка называется master — замени здесь на master

media_folder: "static/uploads"
public_folder: "/uploads"

publish_mode: editorial_workflow

site_url: https://reklamniki.netlify.app # поменяй на свой URL после деплоя

collections:
  - name: "posts"
    label: "Статьи"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    format: "frontmatter"
    extension: "md"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Дата", name: "date", widget: "datetime" }
      - { label: "Описание", name: "description", widget: "string", required: false }
      - { label: "Основное изображение", name: "thumbnail", widget: "image", required: false }
      - { label: "Теги", name: "tags", widget: "list", required: false }
      - { label: "Контент", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Страницы"
    files:
      - label: "О нас"
        name: "about"
        file: "content/about.md"
        fields:
          - { label: "Заголовок", name: "title", widget: "string" }
          - { label: "Контент", name: "body", widget: "markdown" }

      - label: "Контакты"
        name: "contacts"
        file: "content/contacts.md"
        fields:
          - { label: "Заголовок", name: "title", widget: "string" }
          - { label: "Контент", name: "body", widget: "markdown" }
